# Generated by Django 4.1.3 on 2023-01-24 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='qty',
            new_name='item_qty',
        ),
    ]
