# Generated by Django 4.1.3 on 2023-01-25 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_qty_product_item_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_qty',
            field=models.IntegerField(verbose_name='Item Quantity'),
        ),
    ]
